### ISSUE TITLE
kubernetes deployment got failed duto "exec: \"/greeter-srv\": stat /greeter-srv: no such file or directory": unknown

### ISSUE THREAD

**Issue by SHUFIL** [micro/micro#1020]
I am trying to install Micro in kubernetes, as per your [doc ](https://m3o.com/docs/deploy-kubernetes.html), i can install successfully both deppentency , after that i tryed to do the first deployment file name called greeter.yaml,  
but i getting alway below error , i have used below yaml as per your Doc , first think deployment version not support that is you mensioned in your greeter.yaml file, it is extensions/v1beta1 ,i have changed to  apps/v1 , otherwise it will get that error, so i  changed version then it will create the deployment , but that POD will failed because of below error , Please check that error and reply back
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  <unknown>             default-scheduler  Successfully assigned default/greeter-6d8f78b84b-vthgk to minikube
  Warning  Failed     9m22s (x4 over 10m)   kubelet, minikube  Error: failed to start container "greeter": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/greeter-srv\": stat /greeter-srv: no such file or directory": unknown
  Normal   Pulling    8m36s (x5 over 10m)   kubelet, minikube  Pulling image "micro/go-micro"
  Normal   Pulled     8m32s (x5 over 10m)   kubelet, minikube  Successfully pulled image "micro/go-micro"
  Normal   Created    8m32s (x5 over 10m)   kubelet, minikube  Created container greeter
  Warning  BackOff    5m17s (x20 over 10m)  kubelet, minikube  Back-off restarting failed container
```
kubectl apply -f greeter.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: greeter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: greeter-srv
      micro: service
  template:
    metadata:
      labels:
        name: greeter-srv
        micro: service
    spec:
      containers:
        - name: greeter
          command: [
		"/greeter-srv",
	  ]
          image: micro/go-micro
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: greeter-port
          env:
          - name: MICRO_SERVER_ADDRESS
            value: "0.0.0.0:8080"
          - name: MICRO_BROKER
            value: "nats"
          - name: MICRO_BROKER_ADDRESS
            value: "nats-cluster"
          - name: MICRO_REGISTRY
            value: "etcd"
          - name: MICRO_REGISTRY_ADDRESS
            value: "etcd-cluster-client"
```

kubectnetes version
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

helm version
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```
minikube version
```
minikube version: v1.10.1
commit: 63ab801ac27e5742ae442ce36dff7877dcccb278
```
