### ISSUE TITLE
all the micro related application got faild (exa: micro-api) why ?

### ISSUE THREAD

**Issue by SHUFIL** [micro/micro#1167]
I have installed micro in minikube , micro image used  `micro:v2.9.2` , after deployment micro is started , but all related services got faild, installed nats and etcd along with micro , you can see below all micro PODs are went to CrashLoopBackOff ,please see below logs for this .

```
  Normal   Scheduled  39m                    default-scheduler  Successfully assigned default/micro-web-1593532055-665bd47b59-dsst2 to minikube
  Normal   Created    35m (x4 over 39m)      kubelet, minikube  Created container micro-web
  Warning  Failed     35m (x4 over 39m)      kubelet, minikube  Error: failed to start container "micro-web": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/micro\": stat /micro: no such file or directory": unknown
  Normal   Pulling    34m (x5 over 39m)      kubelet, minikube  Pulling image "micro/go-micro"
  Normal   Pulled     34m (x5 over 39m)      kubelet, minikube  Successfully pulled image "micro/go-micro"
  Warning  BackOff    4m37s (x141 over 37m)  kubelet, minikube  Back-off restarting failed container
```

```
ubuntu@server5:~/kubernetes/helm-install/micro/micro-server$ kubectl get pod
NAME                                         READY   STATUS             RESTARTS   AGE
etcd-0                                       1/1     Running            0          4h50m
micro-api-1593532055-865b88bcf5-nkbrg        0/1     CrashLoopBackOff   13         45m
micro-auth-1593532055-fb57f864b-gmb4n        0/1     CrashLoopBackOff   12         45m
micro-bot-1593532055-5b48cb6554-7cbsx        0/1     CrashLoopBackOff   12         45m
micro-broker-1593532055-7cff976f78-d7kdq     0/1     CrashLoopBackOff   12         45m
micro-config-1593532055-c5444cd-t9l27        0/1     CrashLoopBackOff   12         45m
micro-debug-1593532055-5fc8478bdb-kkx6j      0/1     CrashLoopBackOff   12         45m
micro-init-1593532055-7bbf8674cd-5hb72       0/1     CrashLoopBackOff   13         45m
micro-network-1593532055-67c5bfff46-lfczz    0/1     CrashLoopBackOff   12         45m
micro-proxy-1593532055-77765c987f-tqmlb      0/1     CrashLoopBackOff   12         45m
micro-registry-1593532055-6848bbf946-w25s7   0/1     CrashLoopBackOff   12         45m
micro-router-1593532055-7c875d788b-5v4jk     0/1     CrashLoopBackOff   12         45m
micro-runtime-1593532055-7f87cdc88b-4tg7g    0/1     CrashLoopBackOff   12         45m
micro-store-1593532055-7f45fd4994-zfgb9      0/1     CrashLoopBackOff   12         45m
micro-svc-fcff599bb-4m5j8                    1/1     Running            0          45m
micro-web-1593532055-665bd47b59-dsst2        0/1     CrashLoopBackOff   13         45m
nats-0                                       1/1     Running            9          9d
```

Also i will give you my yaml file for starting micro 

```
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: default
  name: micro-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-svc
  template:
    metadata:
      labels:
        app: micro-svc
    spec:
      containers:
      - name: micro
        image: micro/micro:v2.9.2

        imagePullPolicy: Always
        args: ["--registry", "etcd", "--runtime", "kubernetes", "--registry_address", "etcd-headless.default.svc.cluster.local:2379", "--register_interval", "5", "--register_ttl", "10", "--broker", "nats", "--broker_address", "nats-client:4222", "server"]

        env:
        - name: MICRO_SERVER_ADDRESS
          value: "127.0.0.1:8080"
        - name: MICRO_CONFIG
          value: 127.0.0.1:8080
        - name: MICRO_ENABLE_STATS
          value: "true"
        - name: MICRO_REGISTER_TTL
          value: "60"
        - name: MICRO_REGISTER_INTERVAL
          value: "30"
        - name: MICRO_RUNTIME
          value: kubernetes
        - name: MICRO_BROKER
          value: "nats-cluster:6222"
        - name: MICRO_REGISTRY
          value: "etcd"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-headless.default.svc.cluster.local:2379"
```
