### ISSUE TITLE
Wrapping micro api --handler=rpc around a service in Kubernetes

### ISSUE THREAD

**Issue by EwanValentine** [micro/micro#126]
I have the following containers in Kubernetes: 

```yaml
        containers:
        - name: api
          image: microhq/micro
          args:
            - "api"
            - "--handler=rpc"
          env:
          - name: PORT
            value: "8080"
          - name: ENV
            value: staging
          - name: MICRO_REGISTRY
            value: "kubernetes"
          ports:
          - containerPort: 8080
        - name: booking-service
          image: <redacted>
          imagePullPolicy: Always
          env:
          - name: MICRO_BROKER
            value: "nats"
          - name: MICRO_BROKER_ADDRESS
            value: "nats.staging:4222"
          - name: MICRO_REGISTRY
            value: "kubernetes"
          - name: PORT
            value: "50051"
          - name: ENV
            value: staging
          - name: DB_HOST
            value: <redacted>
          ports:
          - containerPort: 50051
```

And I'm getting an error from the `api` container: `Registry kubernetes not found`. This works locally using mdns. I just wondered if there was anything special I had to do to use Kb as the registry with the `micro api` wrapper? 

Cheers!
