### ISSUE TITLE
Change consul address request from micro inside Docker container

### ISSUE THREAD

**Issue by robinhuy** [micro/micro#149]
I have written an authorize plugin and it worked on localhost.
But when I deploy all codes to Docker, there is an error: The plugin call a request to Consul by localhost address not Consul container.
Error log:  `{"id":"go.micro.client","code":500,"detail":"Get http://127.0.0.1:8500/v1/health/service/auth-service: dial tcp 127.0.0.1:8500: connect: connection refused","status":"Internal Server Error"}`
`service-auth` is my service which using to authorize.

I'm using `docker-compose` to build & run containers:
```
version: '3'
services:
  consul:
    command: -server -bootstrap -rejoin 
    image: progrium/consul:latest
    container_name: "my_consul"
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    restart: always
  micro:
    build: ../micro
    command: command: --registry_address=my_consul:8500 api
    container_name: "my_micro"
    depends_on:
      - consul
    links:
      - auth
    ports:
      - "8080:8080"
    restart: always
  auth:
    build: ../auth-service
    command: --registry_address=my_consul:8500
    container_name: "my_auth"
    depends_on:
      - consul
    restart: always
```
The plugin was built with micro to binary file and push to Docker container. Inside plugin, I call to `auth-service` in `Handler` method:

```
...
type Plugin struct {
	authClient proto.AuthClient
}

func (p *Plugin) Init(ctx *cli.Context) error {
	var client client.Client
	p.authClient = proto.NewAuthClient("auth-service", client)
	return nil
}

func (p *Plugin) Handler() plugin.Handler {
	return func(h http.Handler) http.Handler {
		return http.HandlerFunc(func(rsp http.ResponseWriter, req *http.Request) {
			authenticateResponse, err := p.authClient.
				Authorize(context.Background(), &proto.AuthorizeRequest{})

			if err != nil {
				log.Print(err)  // above error was captured here
				rsp.WriteHeader(http.StatusBadGateway)
				return
			}
                        ...
		})
	}
}
...
```

So I think the error is request to Consul `http://127.0.0.1:8500`, it must be `my_consul:8500`. How to fix it?
