### ISSUE TITLE
Docs on docker

### ISSUE THREAD

**Issue by khwerhahn** [micro/micro#1778]
Hi,

is there a "best practice" example on how to run everything (micro server & services) all in docker? In the docs, I could only find how to run `micro server`.

**Comment by lambdaR** [comment]
hi, check out https://github.com/micro/awesome-micro#projects the last one

**Comment by khwerhahn** [comment]
Thanks @lambdaR for the hint. I also found https://github.com/EwanValentine/shippy/blob/master/docker-compose.yml.

This is my docker-compose file:
```
version: '3'
services:
    micro:
        image: micro/micro
        container_name: micro
        command: server
        ports:
        - "8080-8081:8080-8081/tcp"
        - "2111-2115:2111-2115/tcp"
        environment: 
            - MICRO_LOG_LEVEL=debug
        networks:
        - micro
   
    users:
        container_name: srv_users
        build:
            context: ./users
            dockerfile: Dockerfile
            # target: dev
        ports: 
        - 50051:50051
        restart: unless-stopped
        volumes:             
        - .:/Users/konstantinwerhahn/Go/src/github.com/khwerhahn/micro/users
        depends_on:
        - micro
        - database-postgres
        environment:
            MICRO_ADDRESS: ":50051"
            MICRO_REGISTRY: "mdns"
        networks:
        - micro

    database-postgres:
        image: postgres:13.2
        container_name: postgres
        environment:
        - POSTGRES_USER=${DB_USER}  
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
        - DATABASE_HOST=${DB_HOST} 
        ports:
        - '5432:5432'
        volumes:
        - database_postgres:/var/lib/postgresql/data
        - ./init-db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
        - ./sql/init_extensions.sql:/docker-entrypoint-initdb.d/init_extensions.sql
        networks:
        - micro
        restart: unless-stopped

volumes:
    users:
    database_postgres:

# Networks to be created to facilitate communication between containers
networks:
    micro:
        external: true
```

The problem I'm encountering is that my `users` service cannot connect to the `micro` service and thorws the following error: "Error setting up auth: {"Id":"auth.Auth.Generate","Code":401,"Detail":"An account is required","Status":"Unauthorized"}"
