### ISSUE TITLE
Docker: Error setting up auth

### ISSUE THREAD

**Issue by khwerhahn** [micro/micro#1780]
I'm using docker (compose) to spin up the micro environment and services. I get the `Error setting up auth: {"Id":"go.micro.client","Code":500,"Detail":"{\"Id\":\"go.micro.client\",\"Code\":500,\"Detail\":\"service auth: route not found\",\"Status\":\"Internal Server Error\"}","Status":"Internal Server Error"}` error though and I`m not sure how to fix it. 

![Screenshot 2021-05-11 at 13 53 20](https://user-images.githubusercontent.com/3821617/117811037-679ed880-b260-11eb-8410-7194e5e75aed.png)

My `docker-compose` file:
```
version: '3'
services:
    micro:
        image: micro/micro
        container_name: micro
        command: server
        ports:
        - "8080-8081:8080-8081/tcp"
        - "2111-2115:2111-2115/tcp"
        environment: 
            - MICRO_LOG_LEVEL=debug
        networks:
        - micro
    users:
        container_name: srv_users
        build:
            context: ./users
            dockerfile: Dockerfile
            # target: dev
        ports: 
        - 50051:50051
        restart: unless-stopped
        volumes:             
            - .:/Users/konstantinwerhahn/Go/src/github.com/khwerhahn/micro/users
        depends_on:
            - micro
            - database-postgres
        environment:
            - MICRO_AUTH_ID=admin
            - MICRO_AUTH_SECRET=micro
        networks:
        - micro

    database-postgres:
        image: postgres:13.2
        container_name: postgres
        environment:
        - POSTGRES_USER=${DB_USER}  
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
        - DATABASE_HOST=${DB_HOST} 
        ports:
        - '5432:5432'
        volumes:
        - database_postgres:/var/lib/postgresql/data
        - ./init-db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
        - ./sql/init_extensions.sql:/docker-entrypoint-initdb.d/init_extensions.sql
        networks:
        - micro
        restart: unless-stopped

volumes:
    users:
    database_postgres:

networks:
    micro:
        external: true
```
