### ISSUE TITLE
# ./micro services -> Not authorized to perform this request

### ISSUE THREAD

**Issue by clohr-vc** [micro/micro#1861]
**Describe the bug**
We're running micro on an EKS cluster, using the `micro/micro:latest` image to spawn the individual containers. When opening a shell into one of the containers (i.e. `api-latest`) and calling `./micro services`, we receive a `Not authorized to perform this request` error.

We've seen a bunch of reports about this on Windows machines, but nothing for docker images so far.

**To Reproduce**
1. Create an AWS EKS cluster
2. Deploy the `micro/micro:latest` image, using the attached `micro.yaml` specifications **or** https://artifacthub.io/packages/helm/micro/micro
3. Open a shell into one of the running containers once deployed
4. Execute `./micro services`

**Expected behavior**
A list of all registered services should be printed.

**Screenshots**
![image](https://user-images.githubusercontent.com/92918257/140908914-4804c114-2216-4de7-96c2-44042102e4e4.png)

![image](https://user-images.githubusercontent.com/92918257/141126577-0a672309-07fb-4ae2-853e-456e58dbd894.png)

**micro.yaml**
```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: micro
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: store-pv
  namespace: micro
  labels:
    project: micro
spec:
  claimRef:
    name: store-pvc
    namespace: micro
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: store-pvc
  namespace: micro
  labels:
    project: micro
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: micro
  namespace: micro
  labels:
    project: micro
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: micro
  namespace: micro
  labels:
    project: micro
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - services
  - secrets
  - namespaces
  verbs:
  - get
  - create
  - update
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - update
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - pods/logs
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicy
  - networkpolicies
  verbs:
  - get
  - create
  - update
  - delete
  - deletecollection
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: micro
  namespace: micro
  labels:
    project: micro
subjects:
- kind: ServiceAccount
  name: micro
  namespace: micro
roleRef:
  kind: ClusterRole
  name: micro
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: micro
  namespace: micro
  labels:
    project: micro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: micro
subjects:
- kind: ServiceAccount
  name: micro
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: micro
  name: micro
  labels:
    project: micro
spec:
  template:
    spec:
      serviceAccountName: micro
      containers:
      - name: micro
        env:
        - name: MICRO_PROFILE
          value: kubernetes
        - name: MICRO_PROXY
          value: "network.micro.svc.cluster.local:8443"
        - name: MICRO_SERVER_IMAGE
          value: micro/micro:latest
        args:
        - server
        image: micro/micro
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/store"
          name: store-mount
      volumes: 
      - name: store-mount
        persistentVolumeClaim:
          claimName: store-pvc
      restartPolicy: OnFailure
```
