### ISSUE TITLE
healthchecks with default health address fails in kubernetes environment causing CrashLoopBackOff

### ISSUE THREAD

**Issue by xmlking** [micro/micro#342]
if `micro` cli health checks are intended for  kubernetes  health checks, the default health address in the code,  is not appropriate.  The following health-check sidecar setup cause infinite   **CrashLoopBackOff**

To overcome this issue, we are forced to add `--address=0.0.0.0:8088` flag, which defeat the purpose having sensible defaults in the code.

 

```
 Warning  Unhealthy  22s (x9 over 46s)  kubelet, docker-desktop  Liveness probe failed: Get http://10.1.1.224:8088/health: dial tcp 10.1.1.224:8088: connect: connection refused
 Normal   Killing    22s (x3 over 40s)  kubelet, docker-desktop  Container health failed liveness probe, will be restarted
```

My health-check sidecar 
```
      containers:
        - name: health
          image: microhq/micro:latest
          args:
            - "health"
            - "--check_service=$(MICRO_SERVER_NAME)"
            - "--check_address=0.0.0.0:8080"
          envFrom:
            - configMapRef:
                name: env-vars
          livenessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 3
            periodSeconds: 3
```
