### ISSUE TITLE
docker deployment  lookup registry on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by wahello** [micro/micro#343]
[Go Micro's doc ](https://micro.mu/docs/deploy-docker.html) writes: 

```
consul:
  command: -server -bootstrap -rejoin 
  image: progrium/consul:latest
  hostname: "registry"
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"
api:
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 api
  build: .
  links:
  - consul
  ports:
  - "8080:8080"
proxy:
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 proxy
  build: .
  links:
  - consul
  ports:
  - "8081:8081"
web:
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 web
  build: .
  links:
  - consul
  ports:
  - "8082:8082"
```

#### I did as the above in file docker-compose.yml, the result is:
```
micro-api_1  | 2019/09/23 02:56:51 Server go.micro.api-9f655299-ea05-4f3e-8c79-b29305f81def register error: Put http://registry:8500/v1/agent/service/register: dial tcp: lookup registry on 127.0.0.11:53: no such host
```
My compose file is:
```
version: "3"

services:
  # Consul is used as local service discovery
  consul:
    networks:
      - back-tier
    image: progrium/consul
    hostname: "registry"
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    expose:
      - '8300'
      - '8301'
      - '8500'
      - '8600'

  # micro api gateway
  micro-api:
    depends_on:
      - consul
    networks:
      - back-tier
      - front-tier

    image: microhq/micro:latest
    command:
      - --register_interval=5
      - --register_ttl=10
      - "api"

    environment:
      PORT: 8080

      MICRO_REGISTRY: consul
      MICRO_REGISTRY_ADDRESS: registry:8500
    ports:
      - "8080:8080"


  micro-web:
    depends_on:
      - consul
    networks:
      - back-tier
      - front-tier
    image: microhq/micro:latest
    command:
      - --register_interval=5
      - --register_ttl=10
      - "web"
      - "ui"
    environment:
      MICRO_REGISTRY: consul
      MICRO_REGISTRY_ADDRESS: registry:8500

    ports:
      - "8082:8082"


networks:
  back-tier:
    driver: bridge
  front-tier:
    driver: bridge


volumes:
  consul_data:
    driver: local
  etcd_data:
    driver: local
```

It seems that docker subset dns not working between containers.

Env:
docker-desktop for mac,
docker info:
```
Client:
 Debug Mode: false

Server:
 Containers: 50
  Running: 38
  Paused: 0
  Stopped: 12
 Images: 115
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.855GiB
 Name: docker-desktop
 ID: ALYP:FLO4:NXMY:HPND:6KKG:ZTPF:ZDAG:24O5:CIEG:EUIR:6LSC:VDEE
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 178
  Goroutines: 179
  System Time: 2019-09-23T03:32:24.957918619Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://dockerhub.azk8s.cn/
  https://gnlj0pya.mirror.aliyuncs.com/
 Live Restore Enabled: false
 Product License: Community Engine


```

**Comment by wahello** [comment]
### This Problem resolved, by:

```
  consul:
    networks:
      back-tier:
        aliases:
          - registry
```
not 
```
hostname: registry
```

 Your document should be revised.
