### ISSUE TITLE
[api gateway] change in my micro_api_namespace blocked the gateway access

### ISSUE THREAD

**Issue by deregnab** [micro/micro#419]
Hello everyone, I am a beginner when it comes to micro so my problem might be a basic one. 

I tried to use the docker image (a previous version which is still using consul because my company's services were created to work with it and we didn't had time to update it yet) inside of a kubernetes cluster.

I'm currently facing the following issue:
Every time a change happens on my api_namespace "io.example.api" (due to an upgrade or a  redeployment of one of the api), I'm not able to call my apis anymore and I ended up stuck when I try to access a path inside of the gateway, existing or not.

It's probably a basic mistake but I'm currently struggling because of it.

Here are the environment variables used (I replaced the real name of the namespace and server)
``` yaml
        - name: MICRO_API_HANDLER
          value: web
        - name: MICRO_API_NAMESPACE
          value: io.example.api
        - name: MICRO_ENABLE_STATS
          value: "true"
        - name: MICRO_LOG_LEVEL
          value: debug
        - name: MICRO_REGISTER_INTERVAL
          value: "5"
        - name: MICRO_REGISTER_TTL
          value: "10"
        - name: MICRO_REGISTRY
          value: consul
        - name: MICRO_SERVER_NAME
          value: io.example.api
```

The consul agent has the following ports opened:
```yaml
   - containerPort: 8500
          name: http
          protocol: TCP
        - containerPort: 8301
          name: serflan
          protocol: TCP
        - containerPort: 8302
          name: serfwan
          protocol: TCP
        - containerPort: 8300
          name: server
          protocol: TCP
        - containerPort: 8600
          name: dns-tcp
          protocol: TCP
        - containerPort: 8600
          name: dns-udp
          protocol: UDP
``` 

The ingresses rules:
```yaml
  rules:
  - host: api.example.io
    http:
      paths:
      - backend:
          serviceName: gateway-staging-svc
          servicePort: 8080
```

and the gateway service port exposure:
```yaml
 ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
```

Thanks in advance for your help.
