### ISSUE TITLE
Failed kubernetes deployment with GKE v1.13.11-gke.14

### ISSUE THREAD

**Issue by rhzs** [micro/micro#490]
I tried the kubernetes deployment guide with GKE v1.13.11-gke.14. 
https://github.com/micro/micro/blob/master/network/config/kubernetes/gcloud.md

It went with a lot of things that I need to tweak (fix).
CMIIW. The following notes I experienced during deployment:
1. There is no explanation how to use Cloudflare DNS and its API. 
2. So, I went with `autocert` and remove the unnecessary Cloudflare settings. 
3. The guide needs to fix where the `helm` tiller is required. Since it is not required in helm 3 or rather specify the helm version is important. 
4. The GKE guides need to increase minimum size `n1-standard-1` is not enough based on my experience. I got insufficient vCPU. Thus, I need to increase my cluster size. 

Right now I am having difficulty to deploy the greeting web example where the deployed service cannot dial the ETCDv3.  

greeter-svc.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: greeter
  namespace: default
  labels:
    app: greeter
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    name: greeter-srv
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-web
  namespace: default
  labels:
    app: greeter-web
spec:
  ports:
  - port: 9090
    protocol: TCP
  selector:
    name: greeter-web
```

greeter-srv.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: greeter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: greeter-srv
  template:
    metadata:
      labels:
        name: greeter-srv
    spec:
      containers:
      - name: greeter
        command: [
          "/greeter-srv",
        ]
        env:
        - name: MICRO_SERVER
          value: "grpc"
        - name: MICRO_SERVER_NAME
          value: "go.micro.srv.greeter"
        - name: MICRO_SERVER_ADDRESS
          value: "0.0.0.0:8080"
        - name: MICRO_REGISTRY
          value: "etcdv3"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-cluster-client"
        image: gcr.io/xxxxx/greeter-srv
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: greeter-port
```

greeter-web.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: greeter-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: greeter-web
  template:
    metadata:
      labels:
        name: greeter-web
    spec:
      containers:
        - name: greeter-web
          command: [
		    "/greeter-web"
          ]
          env:
          - name: MICRO_PROXY
            value: "go.micro.proxy"
          - name: MICRO_REGISTRY
            value: "etcdv3"
          - name: MICRO_REGISTRY_ADDRESS
            value: "etcd-cluster-client"
          image: gcr.io/xxxxxx/greeter-web
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: web-port
```

**Greeter web error log** 
```shell
❯ k logs --tail=200 -f -p greeter-web-555f85f96-vkp8g
2020-01-13 10:13:27.656641 I | Listening on [::]:34171
{"level":"warn","ts":"2020-01-13T10:13:32.657Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-8356bd0a-0da9-4d78-900a-148097d5f12e/etcd-cluster-client","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: address etcd-cluster-client: missing port in address\""}
2020-01-13 10:13:32.657343 I | context deadline exceeded
```

List of services
```
❯ k get services
NAME                    TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                      AGE
etcd-cluster            ClusterIP      None            <none>         2379/TCP,2380/TCP            19h
etcd-cluster-client     ClusterIP      10.43.250.17    <none>         2379/TCP                     19h
etcd-restore-operator   ClusterIP      10.43.241.251   <none>         19999/TCP                    19h
greeter                 ClusterIP      10.43.241.9     <none>         8080/TCP                     9h
greeter-web             ClusterIP      10.43.254.93    <none>         9090/TCP                     5h34m
kubernetes              ClusterIP      10.43.240.1     <none>         443/TCP                      19h
micro-api               LoadBalancer   10.43.252.14    34.94.xxx.xxx   443:31448/TCP                11h
micro-broker            ClusterIP      10.43.250.77    <none>         8001/TCP                     11h
micro-gateway           ClusterIP      10.43.245.91    <none>         8080/TCP                     11h
micro-network           LoadBalancer   10.43.253.32    34.94.xxx.xxx   8085:30567/UDP               11h
micro-proxy             ClusterIP      10.43.251.245   <none>         8081/TCP                     11h
micro-registry          ClusterIP      10.43.240.110   <none>         8000/TCP                     11h
micro-router            ClusterIP      10.43.252.119   <none>         8084/TCP                     11h
micro-tunnel            NodePort       10.43.240.47    <none>         8083:30036/UDP               11h
micro-web               LoadBalancer   10.43.249.100   34.94.xxx.xxx   443:32297/TCP                11h
nats-cluster            ClusterIP      10.43.242.153   <none>         4222/TCP                     18h
nats-cluster-mgmt       ClusterIP      None            <none>         6222/TCP,8222/TCP,7777/TCP   18h
```

List of pods
```
❯ k get pods
NAME                                                              READY   STATUS             RESTARTS   AGE
etcd-operator-1578842949-etcd-operator-etcd-backup-operatotvzdx   1/1     Running            0          5h17m
etcd-operator-1578842949-etcd-operator-etcd-operator-779bdpkh59   1/1     Running            0          5h17m
etcd-operator-1578842949-etcd-operator-etcd-restore-operatzz6cv   1/1     Running            0          5h17m
greeter-5d4d9d986-cs9lc                                           1/1     Running            0          5h39m
greeter-web-555f85f96-vkp8g                                       0/1     CrashLoopBackOff   6          10m
micro-api-7d8c65469b-2vbhj                                        1/1     Running            0          10h
micro-api-7d8c65469b-52zsp                                        1/1     Running            3          5h17m
micro-api-7d8c65469b-82gmn                                        1/1     Running            3          5h17m
micro-bot-758d9c8846-nzqc9                                        0/1     CrashLoopBackOff   66         5h17m
micro-broker-6d5bcbdd89-2f7dg                                     1/1     Running            3          5h17m
micro-broker-6d5bcbdd89-kbvvb                                     1/1     Running            3          5h17m
micro-broker-6d5bcbdd89-mscn2                                     1/1     Running            3          5h17m
micro-debug-79b59796d4-qqqvv                                      0/1     CrashLoopBackOff   65         5h17m
micro-debug-web-79c74f8ddc-bj6sz                                  1/1     Running            0          10h
micro-init-595c7dd764-jf9qc                                       1/1     Running            0          10h
micro-monitor-5d8d5889b8-8hdj8                                    1/1     Running            3          5h17m
micro-network-7bfff7cb87-4t574                                    0/1     CrashLoopBackOff   64         5h17m
micro-network-7bfff7cb87-qrpwn                                    1/1     Running            0          10h
micro-network-7bfff7cb87-w5rk8                                    0/1     CrashLoopBackOff   64         5h17m
micro-network-api-8cc6bcc89-jtv7d                                 1/1     Running            2          5h17m
micro-network-web-76d797c747-j7mn6                                1/1     Running            0          10h
micro-proxy-66649877b5-6dfnt                                      1/1     Running            3          5h17m
micro-proxy-66649877b5-qwp7m                                      1/1     Running            3          5h17m
micro-proxy-66649877b5-v5nbh                                      1/1     Running            2          5h17m
micro-registry-7c6c98b7cd-qmqgv                                   1/1     Running            0          10h
micro-router-6cc45fcbb-ctk57                                      1/1     Running            0          10h
micro-runtime-7d9bd4f4f5-ptddm                                    1/1     Running            3          5h17m
micro-store-7ffd5cfbdb-zvkl7                                      0/1     CrashLoopBackOff   66         5h17m
micro-tunnel-68b877c957-mcgcs                                     0/1     CrashLoopBackOff   65         5h17m
micro-web-59b8c7464-b9xvk                                         1/1     Running            0          10h
nats-cluster-1                                                    1/1     Running            0          5h16m
nats-cluster-2                                                    1/1     Running            0          5h16m
nats-cluster-3                                                    1/1     Running            0          5h16m
nats-operator-7dcd546854-k5snb                                    1/1     Running            0          5h17m
```
