### ISSUE TITLE
Service not found in micro 1.18.0

### ISSUE THREAD

**Issue by ilhameq** [micro/micro#495]
This is my docker-compose file:

```
version: "3.7"
services:
  etcd:
    container_name: etcd
    image: "bitnami/etcd:latest"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 4001:4001
      - 2380:2380
      - 2379:2379
    networks:
      - micro-net
 micro:
    container_name: micro
    command: --registry=etcd --registry_address=etcd:2379 api  --namespace=go.micro.example.srv --handler=http
    image: micro/micro
    ports:
      - "8080:8080"
    networks:
      - micro-net
luna:
    container_name: luna
    build:
      context: ./luna
      dockerfile: Dockerfile
    depends_on:
      - etcd
      - lunadb
      - registrator
    command: ["./wait_for_postgres.sh", "lunadb", "/usr/local/bin/app"]
    ports:
      - "8088:8080"
    networks:
      - micro-net 

```

When I run micro api from local it works,but it does not work in docker container and i get 

```
{
    "id": "go.micro.example.srv",
    "code": 500,
    "detail": "service not found",
    "status": "Internal Server Error"
}

```
