### ISSUE TITLE
registry not found

### ISSUE THREAD

**Issue by gaspire** [micro/micro#558]
i use docker-compose to deploy api gateway:
```
version: "3.5"
services:
  consul:
    image: consul:latest
    command: agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    restart: always
    networks:
      - go-micro-api
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8500:8500"
  api:
    image: microhq/micro:latest
    command: --registry_address=consul:8500 api --handler=rpc
    restart: always
    depends_on:
      - consul
    networks:
      - go-micro-api
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
    environment:
      - MICRO_NAMESPACE=go.micro.srv
      - MICRO_API_HANDLER=rpc
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul:8500
networks:
    go-micro-api:
      name: docker-go-micro
```

micro api service start fail, output registry not found, help !!!
